### ISSUE TITLE
[BUG] Index SafeProxyFactory

### ISSUE THREAD

**Issue by diegoalzate** [hoprnet/safe-charts#1]
### Overview
When querying `/api/v1/owners/:ownerAddress/safes/` it does not return the safes created by the [HoprNodeStakeFactory](https://gnosisscan.io/address/0x060cb76c6541bf28f94088e658e4167966e37ef9) `.clone`

#### example
- [transaction](https://gnosisscan.io/tx/0xec13de7317dcbaae5efd46a4453739d7d138bf76f95905051fcbdc49b4105315) created a [new safe](https://gnosisscan.io/address/0x9124acd8ae23c86355e6d764ad1bfc413e5f1ddc) with owner 0x90e03535c75f4d18786dc2d29c5e1261782c8943. This new safe should show up when querying [/api/v1/owners/0x90E03535c75f4D18786dC2d29c5e1261782C8943/safes/](https://safe-transaction.stage.hoprtech.net//api/v1/owners/0x90E03535c75f4D18786dC2d29c5e1261782C8943/safes/)

#### steps to recreate
1. Execute [HoprNodeStakeFactory](https://gnosisscan.io/address/0x060cb76c6541bf28f94088e658e4167966e37ef9) `.clone`
2. Query `/api/v1/owners/:ownerAddress/safes/` to see if the created safe shows up

#### Possible solution
>  the safe transaction service is indexing "GnosisSafeProxyFactory" (0xa6b71e26c5e0845f74c812102ca7114b6a896ab2) which is of safe v1.3.0. However, our smart contracts uses "SafeProxyFactory" (0x4e1dcf7ad4e460cfd30791ccc4f9c8a4f820ec67) which is of safe v1.4.x

**Comment by ausias-armesto** [comment]
Hi @diegoalzate, would these lines confirm your suspicion ?

https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/indexers/safe_events_indexer.py#L138

**Comment by diegoalzate** [comment]
> Hi @diegoalzate, would these lines confirm your suspicion ?
> 
> https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/indexers/safe_events_indexer.py#L138

I think so. It does look like it gets only v1.3

**Comment by ausias-armesto** [comment]
In a debugging session with @QYuQianchen we have realised that the contract [SafeProxyFactory 1.4.0](https://gnosisscan.io/address/0x4e1dcf7ad4e460cfd30791ccc4f9c8a4f820ec67) was not added as contract in the safe-transaction-service. After [adding the contract](https://safe-transaction.stage.hoprtech.net/admin/contracts/contract/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67/change/?_changelist_filters=q%3DProxyFactory) and associating it with the [318 GnosisSafeProxyFactory] Contract ABI  , then the URL https://safe-transaction.stage.hoprtech.net//api/v1/safes/0x29180976eF82dDc2C1d6d3D249F36184F96aDeBC/ now works as tested by @diegoalzate 

This is the [record created](https://safe-transaction.stage.hoprtech.net/admin/contracts/contract/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67/change/?_changelist_filters=q%3DProxyFactory)

On the other hand the query to know the **safes** of a given owner it still does not work [/api/v1/owners/0x90E03535c75f4D18786dC2d29c5e1261782C8943/safes/](https://safe-transaction.stage.hoprtech.net//api/v1/owners/0x90E03535c75f4D18786dC2d29c5e1261782C8943/safes/)

The master copy associated with the safe is `[0xc962E67D9490E154D81181879ddf4CD3b65D2132](https://safe-transaction.stage.hoprtech.net/admin/history/safemastercopy/)` which is not being indexed for some unknown reason.

On the other side, I have notice that the [Gnosis Chain](https://safe-config.stage.hoprtech.net/admin/chains/chain/100/change/) in safe-config-service is configured to work with **L2** and **1.3.0** as recommended master copy version. Chainging those parameters may be the solution 
^^ @tolbrino

**Comment by QYuQianchen** [comment]
Will deploy another set of contracts that's compatible with 1.4.1 for testing.

**Comment by diegoalzate** [comment]
With the new contracts this issue still persists 

> On the other hand the query to know the safes of a given owner it still does not work [/api/v1/owners/0x90E03535c75f4D18786dC2d29c5e1261782C8943/safes/](https://safe-transaction.stage.hoprtech.net//api/v1/owners/0x90E03535c75f4D18786dC2d29c5e1261782C8943/safes/)

and the other api endpoint to get info still works: https://safe-transaction.stage.hoprtech.net//api/v1/safes/0xf484C2489f16a18f2e8c9b3ED49449e1950845c3/

@ausias-armesto

**Comment by QYuQianchen** [comment]
Updated the ABI to test if the backend can pick up `AddedOwner`. I'll check their source code at the same time

**Comment by ausias-armesto** [comment]
By reviewing the code I've seen that the method `/api/v1/safes/{safe-address}` retrieves the code from [here](https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/services/safe_service.py#L151) and is getting the data directly from the blockchain on the other side the method `/api/v1/owners/{owner-addres}/safes/` retrieves the code from [here](https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/models.py#L1871) and it is gathering the data from the database table `SafeStatus`

The indexer uses this [Task](https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/tasks.py#L379) to process all the Safe transactions and process the data from the database table `Internal Tx decoded`. By inspecting the misconfigured [safe](https://safe-transaction.stage.hoprtech.net/admin/history/internaltxdecoded/?q=0x307913e66786e490838B72C92e675636F64D86Ad) we can observed that there have been 3 txs, and the owner received from the transaction is already the wrong owner.

 
<img width="1195" alt="Screenshot 2023-08-21 at 17 59 33" src="https://github.com/hoprnet/safe-charts/assets/29434949/512be9da-4880-4566-9d5c-e2c7ba6e74bc">


The previous method `/api/v1/owners/{owner-addres}/safes/` will look at the table `SafeStatus` but, at this point, all the events submitted by the SC have been with the wrong owner. And although one event is to change the ownership, the event was submitted by the NodeStakeFactory owner.



Which leads me to the conclusion that the solution might be modifying something at the StakeFactory.
Is there a way to submit at least one last event with the new owner?
https://github.com/hoprnet/hoprnet/blob/master/packages/ethereum/contracts/src/node-stake/NodeStakeFactory.sol#L136

**Comment by QYuQianchen** [comment]
Thanks for digging into their source code and for finding all those details! @ausias-armesto 

The `owner` received from the `setup` [function](https://safe-transaction.stage.hoprtech.net/admin/history/internaltxdecoded/?q=0x307913e66786e490838B72C92e675636F64D86Ad) was indeed the correct the owner at setup, which is the StakeFactory contract address. This event was emitted by the SafeFactory contract.
The only other internal transactions that were indexed are `approveHash`. It shows that the indexer looped many internal transactions. From [gnosisscan](https://gnosisscan.io/tx/0x3212b768d023d68c76346e2402909b9095f71411e22a46e286e969688ec0020e/advanced#internal), you can see that there are 8 internal txs on address 0x307913e66786e490838B72C92e675636F64D86Ad whereas the backend only got 3. The looped ones contained function calls like `removeOwner` and `swapOwner`.

So next step is to figure out why `swapOwner` function or the `AddedOwner` events on safe proxies were not properly indexed.

Regarding the proposal of adding event in StakeFactory: This will not help because safe transaction service does not index StakeFactory, but rather SafeProxyFactory (deployed by Safe) and created safe proxy instances (bytecode is created by Safe). Events emitted in StakeFactory doesn't have impact on Safe Transaction Service.

**Comment by ausias-armesto** [comment]
@Tino has customised the service-transaction-service to accept contract 1.4.1 and now seems to be working 
@diegoalzate can you check as well

**Comment by diegoalzate** [comment]
@ausias-armesto yes it seems to be working now 👍
